---
# tasks file for nexus_delete
 - name: debug name variables
   ansible.builtin.debug:
      msg: Variable {{ kri_go_packages_version[item].version }} is defined
   with_items: "{{ kri_go_packages_list }}"

 - name: create script nexus
   template:
      src: clean_nexus.sh.j2
      dest: /tmp/clean_nexus.sh
      owner: "admin"
      group: "admin"
      mode: "755"
 - name: create inventory nexus
   template:
      src: inventory.j2
      dest: /tmp/inventory
      owner: "admin"
      group: "admin"
      mode: "744"