---
# tasks file for domain_join

- name: Check if block exists in file
  lineinfile:
    path: /home/admin/file.txt
    regexp: '^\s*server 10\.15\.85\.[567] iburst'
    state: present
    create: yes
  register: block_check
  become: yes

- name: "add strings"
  blockinfile:
    path: /home/admin/file.txt
    block: |
        # Use public servers from the pool.ntp.org project.
        # Please consider joining the pool (http://www.pool.ntp.org/join.html).
        
        # Record the rate at which the system clock gains/losses time.
        driftfile /var/lib/chrony/drift
        
        # Allow the system clock to be stepped in the first three updates
        # if its offset is larger than 1 second.
        makestep 1.0 3
        
        # Enable kernel synchronization of the real-time clock (RTC).
        rtcsync
        
        # Enable hardware timestamping on all interfaces that support it.
        #hwtimestamp *
        
        # Increase the minimum number of selectable sources required to adjust
        # the system clock.
        #minsources 2
        
        # Allow NTP client access from local network.
        #allow 192.168.0.0/16
        
        # Serve time even if not synchronized to a time source.
        #local stratum 10
        
        # Specify file containing keys for NTP authentication.
        #keyfile /etc/chrony.keys
        
        # Specify directory for log files.
        logdir /var/log/chrony
        
        # Select which information is logged.
        #log measurements statistics tracking
    state: present
    create: yes
    insertafter: EOF
    marker: ''
  when: line_check.changed
  become: yes