---
# tasks file for test_role

- name: Отладка используемого интерфейса
  debug:
    msg: "Используемый интерфейс: {{ interface }}"

- name: Показать доступные интерфейсы
  debug:
    var: ansible_facts['interfaces']

- name: Получить MAC-адрес интерфейса
  debug:
    msg: "MAC-адрес интерфейса {{ interface }}: {{ ansible_facts[interface]['macaddress'] }}"