---
# tasks file for test_role

- name: Отладка используемого интерфейса
  debug:
    msg: "Используемый интерфейс: {{ mega_interface }}"

- name: Показать доступные интерфейсы
  debug:
    var: ansible_facts['interfaces']

- name: Получить MAC-адрес интерфейса
  debug:
    msg: "MAC-адрес интерфейса {{ mega_interface }}: {{ ansible_facts[mega_interface]['macaddress'] }}"

- name: Вывод хостнейма
  debug:
    msg: "{{ ansible_hostname }}"

- name: Вывод IP
  debug:
    msg: "{{ ansible_host }}"