---
# tasks file for test_role

- name: Отладка используемого интерфейса
  debug:
    msg: "Используемый интерфейс: {{ mega_interface }}"

- name: Показать доступные интерфейсы
  debug:
    var: ansible_facts['interfaces']

- name: Получить MAC-адрес интерфейса
  debug:
    msg: "MAC-адрес интерфейса {{ mega_interface }}: {{ ansible_facts[mega_interface]['macaddress'] }}"

- name: Вывод хостнейма
  debug:
    msg: "{{ ansible_hostname }}"

- name: Вывод IP
  debug:
    msg: "{{ ansible_host }}"

- name: Find route
  find:
    paths: '/etc/sysconfig/network-scripts'
    patterns: "ifcfg-eth*"
  register: manage_network_interface_found_files

- name: Вывод файлов, если файлы найдены
  debug:
    msg: "{{ manage_network_interface_found_files.files }}"
  when: manage_network_interface_found_files.files | length > 0

- name: Вывод файлов
  debug:
    msg: "{{ manage_network_interface_found_files }}"

- name: Вывод файлов
  debug:
    msg: "{{ manage_network_interface_found_files.files[0].path }}"

- name: Execute multiple bash commands
  shell: |
    mkdir {{ test_command1 }} &&
    mkdir {{ test_command2 }} &&
    rm -f /opt/test3
    mkdir /opt/{{ test_mlt_command1 }} &&
    mkdir /opt/test{{ test_mlt_command2 }} &&
    mkdir /opt/test5

- name: Reboot the machine
  reboot:
    msg: "Rebooting for maintenance"
    wait: yes