---
# tasks file for test_role
- name: test task
  debug: msg="{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"

- name: Вывести все факты
  debug:
    var: ansible_facts

- name: test task
  debug: msg="{{ ansible_facts.eth0.macaddress }}"
